;remove from config strings to prevent overflows
; you may use ;  to disable specific lines
;player skins are managed automatically

[categories]
;declare categories
1=remove

[remove]
;red team
sysimg/icons/mp/team_red
sysimg/icons/mp/team_red_hud
sysimg/icons/mp/team_red_spectator
;awards we do not use in coop
sysimg/icons/mp/award_sharpshooter
sysimg/icons/mp/award_untouchable
sysimg/icons/mp/award_logistics
sysimg/icons/mp/award_tactician
sysimg/icons/mp/award_demolitionist
sysimg/icons/mp/award_mvp
sysimg/icons/mp/award_defender
sysimg/icons/mp/award_warrior
sysimg/icons/mp/award_carrier
sysimg/icons/mp/award_interceptor
sysimg/icons/mp/award_bravery
sysimg/icons/mp/award_firstStrike
;Menu sounds
sound/misc/menu/reject.wav
;mp computer voice we do not use in coop
localization/sound/dialog/dm/comp_2mins.mp3
localization/sound/dialog/dm/comp_1min.mp3
localization/sound/dialog/dm/comp_500pointsleft.mp3
localization/sound/dialog/dm/comp_100pointsleft.mp3
localization/sound/dialog/dm/comp_25pointsleft.mp3
localization/sound/dialog/dm/comp_10pointsleft.mp3
localization/sound/dialog/dm/comp_5pointsleft.mp3
localization/sound/dialog/dm/comp_4pointsleft.mp3
localization/sound/dialog/dm/comp_3pointsleft.mp3
localization/sound/dialog/dm/comp_2pointsleft.mp3
localization/sound/dialog/dm/comp_1pointsleft.mp3
localization/sound/dialog/dm/comp_mats.mp3
localization/sound/dialog/dm/comp_tiedfirst.mp3
localization/sound/dialog/dm/comp_winn.mp3
localization/sound/dialog/dm/comp_second.mp3
localization/sound/dialog/dm/comp_third.mp3
localization/sound/dialog/dm/comp_didnotrank.mp3
localization/sound/dialog/dm/comp_matover.mp3
localization/sound/dialog/dm/comp_5mins.mp3
;taunts we do not use in coop
localization/sound/dialog/dm/mp_andor1.mp3
localization/sound/dialog/dm/mp_andor2.mp3
localization/sound/dialog/m10l1/romgate3_cred.mp3
localization/sound/dialog/m10l1/outrom1_ohno.mp3
localization/sound/dialog/dm/mp_borgf1.mp3
localization/sound/dialog/dm/mp_borgf2.mp3
localization/sound/dialog/dm/mp_borgm1.mp3
localization/sound/dialog/dm/mp_borgm2.mp3
localization/sound/dialog/dm/mp_klingf1.mp3
localization/sound/dialog/dm/mp_klingf2.mp3
localization/sound/dialog/dm/mp_inform1.mp3
localization/sound/dialog/dm/mp_inform2.mp3
localization/sound/dialog/dm/mp_rene1.mp3
localization/sound/dialog/dm/mp_rene2.mp3
localization/sound/dialog/dm/mp_krindo1.mp3
localization/sound/dialog/dm/mp_krindo2.mp3
localization/sound/dialog/dm/mp_rom1.mp3
localization/sound/dialog/dm/mp_rom2.mp3
localization/sound/dialog/dm/mp_omag1.mp3
localization/sound/dialog/dm/mp_omag2.mp3
localization/sound/dialog/dm/mp_lurok1.mp3
localization/sound/dialog/dm/mp_lurok2.mp3
localization/sound/dialog/dm/mp_naus1.mp3
localization/sound/dialog/dm/mp_naus2.mp3
localization/sound/dialog/dm/mp_attrexf1.mp3
localization/sound/dialog/dm/mp_attrexf2.mp3
localization/sound/dialog/dm/mp_attrexm1.mp3
localization/sound/dialog/dm/mp_attrexm2.mp3
localization/sound/dialog/dm/mp_kleeya1.mp3
localization/sound/dialog/dm/mp_kleeya2.mp3
localization/sound/dialog/dm/mp_picard1.mp3
localization/sound/dialog/dm/mp_picard2.mp3
localization/sound/dialog/dm/mp_tuvok1.mp3
localization/sound/dialog/dm/mp_tuvok2.mp3