[categories]
;declare categories
1=coopSkins

[coopSkins]
;declare which skins are allowed to be used in coop
;models/char/dm_munro.tik is already hardcoded in the gamecode
models/char/dm_munro.tik
models/char/dm_telsia.tik
models/char/dm_jurot.tik
models/char/dm_chang.tik
models/char/dm_kourban.tik
models/char/dm_chell.tik
models/char/dm_barclay.tik
models/char/dm_picard.tik
models/char/munro_sf.tik
models/char/munro_voyager.tik
models/char/munro-romulan.tik
models/char/munro_evosuit.tik
models/char/eb_gonzales.tik
models/char/dm_tuvok.tik
models/char/dm_attrexian_security-male.tik
models/char/dm_drull_Kleeya.tik
models/char/dm_ferengi_oolpax.tik
models/char/dm_klingon_merc-boss.tik
models/char/dm_nausicaan_male-merc.tik
models/char/dm_drull_krindo.tik
models/char/dm_attrexian_command-female.tik