float fThreadTime;

void main();
void keypad1_solved();

void keypad_runThread(entity eActivator, string sThread);

void keypad_runThread(entity eActivator, string sThread)
//start thread, if possible also give Entity who damaged Barrel
{
	if(sThread == ""){
		return;
	}
	
	entity eTrigger;
	eTrigger = spawn("trigger_relay","thread",sThread,"cnt","1");
	wait(0.05);
	if(doesEntityExist(eTrigger)){
		if(doesEntityExist(eActivator)){
			eTrigger.doActivate(eActivator);
			return;
		}

		triggerEntity(eTrigger);
	}
}

float keypad_validEntity(entity eTarget, string sBaseName)
{
	if(!doesEntityExist(eTarget)){
		return 0;
	}
	if(sBaseName == ""){
		return 0;
	}
	
	string sTargetName;
	sTargetName = eTarget.getRawTargetName();
	
	float iButton;
	for(iButton=0;iButton<=11;iButton++){
		if(sBaseName+"_"+iButton == sTargetName){
			return 1;
		}
	}
	
	return 0;
}

void keypad_clear(entity eTrigger, string sBaseName, string sText)
{
	if(!doesEntityExist(eTrigger)){
		return;
	}
	if(sBaseName == ""){
		return;
	}
	
	//show all input buttons
	entity eButton;
	float iButton;
	for(iButton=0;iButton<=11;iButton++){
		eButton = getEntity(sBaseName+"_"+iButton);
		if(doesEntityExist(eButton)){
			eButton.show();
		}
	}
	//hide entered digit symbol
	for(iButton=12;iButton<=17;iButton++){
		eButton = getEntity(sBaseName+"_"+iButton);
		if(doesEntityExist(eButton)){
			eButton.hide();
		}
	}
	
	entity eText;
	entity eReady;
	eReady = getEntity(sBaseName+"_ready");
	eText = getEntity(sBaseName+"_"+sText);
	if(doesEntityExist(eText)){
		if(doesEntityExist(eReady)){
			eText.warp(eReady.getOrigin());
		}
		eText.show();
	}
	
	//show entered digit empty symbol
	for(iButton=1;iButton<=6;iButton++){
		eButton = getEntity(sBaseName+"_pos"+iButton);
		if(doesEntityExist(eButton)){
			eButton.hide();
		}
	}	

	//solved or failed
	if(eTrigger.getFloatVar("keypadSolved") == 1 || eTrigger.getFloatVar("keypadFailed") == 1){
		entity eMarker;
		eMarker = getEntity(sBaseName+"_marker");
		if(doesEntityExist(eMarker)){
			eMarker.hide();
		}
		return;
	}
	
	wait(0.25);
	
	eTrigger.setFloatVar("keypadCodepos",1);
	if(doesEntityExist(eText)){
		if(doesEntityExist(eReady)){
			eText.warp(eReady.getOrigin());
			eReady.show();
		}
		eText.hide();
		
	}

	wait(0.25);
	
	//show entered digit empty symbol
	for(iButton=1;iButton<=6;iButton++){
		eButton = getEntity(sBaseName+"_pos"+iButton);
		if(doesEntityExist(eButton)){
			eButton.show();
		}
	}	
	
	if(doesEntityExist(eReady)){
		eReady.hide();
	}
}

void keypad_abbort(entity eTrigger, entity ePlayer, string sBaseName)
{
	if(doesEntityExist(ePlayer)){
		ePlayer.safeholster(0);
		ePlayer.disableuseweapon(0);
	}
	
	if(!doesEntityExist(eTrigger)){
		print("keypad_abbort: eTrigger missing\n");
		return;
	}

	entity eMarker;
	eMarker = getEntity(sBaseName+"_marker");
	
	if(doesEntityExist(eMarker)){
		eMarker.hide();
	}
	
	keypad_clear(eTrigger,sBaseName,"error");
	eTrigger.triggerable();
}


void keypad_manage(entity eTrigger, entity ePlayer)
{
	string sBaseName;
	string sCode;
	string sThread;
	if(!doesEntityExist(eTrigger)){
		print("keypad_manage: eTrigger missing\n");
		return;
	}
	if(!doesEntityExist(ePlayer)){
		print("keypad_manage: ePlayer missing\n");
		return;
	}
	sBaseName = eTrigger.getStringvar("uservar1");
	if(sBaseName == ""){
		print("keypad_manage: uservar1 for baseName is empty\n");
		return;
	}	
	sCode = eTrigger.getStringvar("uservar2");
	if(sCode == ""){
		print("keypad_manage: uservar2 for code is empty\n");
		return;
	}
	sThread = eTrigger.getStringvar("uservar3");
	if(sThread == ""){
		print("keypad_manage: uservar3 for thread is empty\n");
		return;
	}
	
	entity eMarker;
	entity eMarkerSelected;
	entity eCodePos;
	float bMarkerVisible;
	vector vTrigger;
	vector vPlayer;
	float bCleared;
	string sInputChain;
	entity eEntered;
	entity eTarget;
	float iCodePos;
	entity eReady;
	string sText;
	float iFailures;
	float iMaxFailure;
	
	iMaxFailure		= eTrigger.getFloatVar("uservar4");
	eReady			= getEntity(sBaseName+"_ready");
	eMarker			= getEntity(sBaseName+"_marker");
	eMarkerSelected = getEntity(sBaseName+"_markerSelected");
	vTrigger		= eTrigger.getOrigin();
	
	if(doesEntityExist(eReady)){
		eReady.hide();
	}
	
	if(doesEntityExist(eMarker)){
		eMarker.notsolid();
	}
	if(doesEntityExist(eMarkerSelected)){
		eMarkerSelected.notsolid();
	}
	
	//ePlayer.disableinventory(1);
	ePlayer.safeholster(1);
	ePlayer.disableuseweapon(1);
	
	while(1){
		if(!doesEntityExist(eTrigger)){
			return;
		}
		
		if(!doesEntityExist(ePlayer)){
			keypad_abbort(eTrigger, $null, sBaseName);
			return;
		}
		
		if(ePlayer.getHealth() <= 0 || ePlayer.coop_isSpectator() == 1){
			keypad_abbort(eTrigger, ePlayer, sBaseName);
			return;
		}
		
		vPlayer = ePlayer.getOrigin();
		if(vectorLength(vTrigger - vPlayer) > 64){
			keypad_abbort(eTrigger, ePlayer, sBaseName);
			return;
		}
		eTarget = ePlayer.coop_getTargetedEntity();
		if(doesEntityExist(eTarget)){
			if(doesEntityExist(eMarker)){
				if(eTarget.getRawTargetName() == "world"){
					eMarker.hide();
					bMarkerVisible = 0;
					wait(0.1);
				}
				else if (keypad_validEntity(eTarget,sBaseName)){				
					eMarker.warp(eTarget.getOrigin());
					
					if(bMarkerVisible){
						if(ePlayer.coop_checkFire() == 1 || ePlayer.coop_checkUse() ){							
							iCodePos = eTrigger.getFloatVar("keypadCodepos");
							if(iCodePos > 6){
								iCodePos = 6;
							}
							
							string sInput;
							sInput = eTarget.getStringVar("uservar1");
							
							//clear code - basically abbort
							if(sInput == "C"){
								sInput = "";
								bCleared = 1;
								sInputChain = "";
								iCodePos = 0;
								keypad_clear(eTrigger, sBaseName,"clear");
							}
							
							//accept code
							else if(sInput == "asterisk"){		
								sInput = "";

								//check if code is correct
								if(sCode == sInputChain){
									sText = "ok";
									eTrigger.setFloatVar("keypadSolved",1);
									thread keypad_runThread(ePlayer,sThread);
								}else{
									sText = "error";

									if(iMaxFailure > 0){
										iFailures = eTrigger.getFloatVar("keypadFailures");
										iFailures++;
										
										if(iFailures >= iMaxFailure){
											eTrigger.setFloatVar("keypadFailed",1);
											//if(doesEntityExist(eMarker)){
												//eMarker.selfDetonate();
											//}
										}
									}
									eTrigger.setFloatVar("keypadFailures",iFailures);
								}
								bCleared = 1;
								sInputChain = "";
								iCodePos = 0;
								
								if(doesEntityExist(ePlayer)){
									ePlayer.safeholster(0);
									ePlayer.disableuseweapon(0);
								}
								
								keypad_clear(eTrigger, sBaseName, sText);
								return;
							}
							
							sInputChain = (sInputChain + sInput);
							//ePlayer.hudprint("You selected: "+sInput+"\n");
							
							if(!bCleared){
								eMarker.hide();
								bMarkerVisible = 0;
								
								if(doesEntityExist(eMarkerSelected)){
									eMarkerSelected.warp(eTarget.getOrigin());
									eMarkerSelected.show();
									eCodePos = getEntity(sBaseName+"_pos"+iCodePos);
									if(doesEntityExist(eCodePos)){
										eCodePos.hide();
										eTarget.warp(eCodePos.getOrigin());
									}
									else{
										eTarget.hide();
									}
								}
								
								wait(0.35);
								
								eEntered = getEntity(sBaseName+"_"+(11+iCodePos));
								if(doesEntityExist(eEntered)){
									eEntered.warp(eTarget.getOrigin());
									eEntered.show();
								}
								
								if(doesEntityExist(eTarget)){
									if(doesEntityExist(eMarkerSelected)){
										eTarget.warp(eMarkerSelected.getOrigin());
									}
									else{
										eTarget.show();
									}
								}							
								if(doesEntityExist(eMarkerSelected)){
									eMarkerSelected.hide();
								}
								
								iCodePos++;
								eTrigger.setFloatVar("keypadCodepos",iCodePos);
							}
							bCleared=0;
						}
					}
					
					if(!bMarkerVisible){
						bMarkerVisible = 1;
						eMarker.show();
					}
				}
			}
		}else{
			eMarker.hide();
			bMarkerVisible = 0;
		}
		
		wait(0.05);
	}
}

void keypad_start()
{
	if( (fThreadTime + 1) > getLevelTime() ){
		return;
	}
	fThreadTime = getLevelTime();
	
	entity eTrigger;
	eTrigger = getCurrentEntity();
	if(!doesEntityExist(eTrigger)){
		return;
	}
	
	//disable input
	eTrigger.notTriggerable();
	eTrigger.setFloatVar("keypadCodepos",1);
	eTrigger.setFloatVar("keypadSolved",0);
	
	//prevent issues with getCurrentEntity out of range
	eTrigger = eTrigger;
	
	vector vTrigger;
	vector vPlayer;
	vTrigger = eTrigger.getOrigin();
	
	entity ePlayer;
	ePlayer = eTrigger.getLastActivatingEntity();
	if(doesEntityExist(ePlayer)){
		keypad_manage(eTrigger, ePlayer);
	}
	
	if(!doesEntityExist(eTrigger)){
		return;
	}
	
	if(eTrigger.getFloatVar("keypadSolved")){
		return;
	}
	if(eTrigger.getFloatVar("keypadFailed")){
		return;
	}
	
	eTrigger.triggerable();
}

void main()
{

}

void keypad1_solved()
{
	entity eDoor;
	eDoor = getEntity("door");
	if(doesEntityExist(eDoor)){
		triggerEntity(eDoor);
	}
}